# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.25.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.25.1/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/alvisestella/Desktop/Ship

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/alvisestella/Desktop/Ship

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.25.1/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.25.1/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/alvisestella/Desktop/Ship/CMakeFiles /Users/alvisestella/Desktop/Ship//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/alvisestella/Desktop/Ship/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ship

# Build rule for target.
ship: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ship
.PHONY : ship

# fast build rule for target.
ship/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ship.dir/build.make CMakeFiles/ship.dir/build
.PHONY : ship/fast

Bot.o: Bot.cpp.o
.PHONY : Bot.o

# target to build an object file
Bot.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ship.dir/build.make CMakeFiles/ship.dir/Bot.cpp.o
.PHONY : Bot.cpp.o

Bot.i: Bot.cpp.i
.PHONY : Bot.i

# target to preprocess a source file
Bot.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ship.dir/build.make CMakeFiles/ship.dir/Bot.cpp.i
.PHONY : Bot.cpp.i

Bot.s: Bot.cpp.s
.PHONY : Bot.s

# target to generate assembly for a file
Bot.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ship.dir/build.make CMakeFiles/ship.dir/Bot.cpp.s
.PHONY : Bot.cpp.s

Corazzata.o: Corazzata.cpp.o
.PHONY : Corazzata.o

# target to build an object file
Corazzata.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ship.dir/build.make CMakeFiles/ship.dir/Corazzata.cpp.o
.PHONY : Corazzata.cpp.o

Corazzata.i: Corazzata.cpp.i
.PHONY : Corazzata.i

# target to preprocess a source file
Corazzata.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ship.dir/build.make CMakeFiles/ship.dir/Corazzata.cpp.i
.PHONY : Corazzata.cpp.i

Corazzata.s: Corazzata.cpp.s
.PHONY : Corazzata.s

# target to generate assembly for a file
Corazzata.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ship.dir/build.make CMakeFiles/ship.dir/Corazzata.cpp.s
.PHONY : Corazzata.cpp.s

Main1.o: Main1.cpp.o
.PHONY : Main1.o

# target to build an object file
Main1.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ship.dir/build.make CMakeFiles/ship.dir/Main1.cpp.o
.PHONY : Main1.cpp.o

Main1.i: Main1.cpp.i
.PHONY : Main1.i

# target to preprocess a source file
Main1.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ship.dir/build.make CMakeFiles/ship.dir/Main1.cpp.i
.PHONY : Main1.cpp.i

Main1.s: Main1.cpp.s
.PHONY : Main1.s

# target to generate assembly for a file
Main1.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ship.dir/build.make CMakeFiles/ship.dir/Main1.cpp.s
.PHONY : Main1.cpp.s

Mare.o: Mare.cpp.o
.PHONY : Mare.o

# target to build an object file
Mare.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ship.dir/build.make CMakeFiles/ship.dir/Mare.cpp.o
.PHONY : Mare.cpp.o

Mare.i: Mare.cpp.i
.PHONY : Mare.i

# target to preprocess a source file
Mare.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ship.dir/build.make CMakeFiles/ship.dir/Mare.cpp.i
.PHONY : Mare.cpp.i

Mare.s: Mare.cpp.s
.PHONY : Mare.s

# target to generate assembly for a file
Mare.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ship.dir/build.make CMakeFiles/ship.dir/Mare.cpp.s
.PHONY : Mare.cpp.s

Nds.o: Nds.cpp.o
.PHONY : Nds.o

# target to build an object file
Nds.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ship.dir/build.make CMakeFiles/ship.dir/Nds.cpp.o
.PHONY : Nds.cpp.o

Nds.i: Nds.cpp.i
.PHONY : Nds.i

# target to preprocess a source file
Nds.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ship.dir/build.make CMakeFiles/ship.dir/Nds.cpp.i
.PHONY : Nds.cpp.i

Nds.s: Nds.cpp.s
.PHONY : Nds.s

# target to generate assembly for a file
Nds.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ship.dir/build.make CMakeFiles/ship.dir/Nds.cpp.s
.PHONY : Nds.cpp.s

Players.o: Players.cpp.o
.PHONY : Players.o

# target to build an object file
Players.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ship.dir/build.make CMakeFiles/ship.dir/Players.cpp.o
.PHONY : Players.cpp.o

Players.i: Players.cpp.i
.PHONY : Players.i

# target to preprocess a source file
Players.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ship.dir/build.make CMakeFiles/ship.dir/Players.cpp.i
.PHONY : Players.cpp.i

Players.s: Players.cpp.s
.PHONY : Players.s

# target to generate assembly for a file
Players.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ship.dir/build.make CMakeFiles/ship.dir/Players.cpp.s
.PHONY : Players.cpp.s

Sde.o: Sde.cpp.o
.PHONY : Sde.o

# target to build an object file
Sde.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ship.dir/build.make CMakeFiles/ship.dir/Sde.cpp.o
.PHONY : Sde.cpp.o

Sde.i: Sde.cpp.i
.PHONY : Sde.i

# target to preprocess a source file
Sde.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ship.dir/build.make CMakeFiles/ship.dir/Sde.cpp.i
.PHONY : Sde.cpp.i

Sde.s: Sde.cpp.s
.PHONY : Sde.s

# target to generate assembly for a file
Sde.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ship.dir/build.make CMakeFiles/ship.dir/Sde.cpp.s
.PHONY : Sde.cpp.s

Ship.o: Ship.cpp.o
.PHONY : Ship.o

# target to build an object file
Ship.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ship.dir/build.make CMakeFiles/ship.dir/Ship.cpp.o
.PHONY : Ship.cpp.o

Ship.i: Ship.cpp.i
.PHONY : Ship.i

# target to preprocess a source file
Ship.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ship.dir/build.make CMakeFiles/ship.dir/Ship.cpp.i
.PHONY : Ship.cpp.i

Ship.s: Ship.cpp.s
.PHONY : Ship.s

# target to generate assembly for a file
Ship.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ship.dir/build.make CMakeFiles/ship.dir/Ship.cpp.s
.PHONY : Ship.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ship"
	@echo "... Bot.o"
	@echo "... Bot.i"
	@echo "... Bot.s"
	@echo "... Corazzata.o"
	@echo "... Corazzata.i"
	@echo "... Corazzata.s"
	@echo "... Main1.o"
	@echo "... Main1.i"
	@echo "... Main1.s"
	@echo "... Mare.o"
	@echo "... Mare.i"
	@echo "... Mare.s"
	@echo "... Nds.o"
	@echo "... Nds.i"
	@echo "... Nds.s"
	@echo "... Players.o"
	@echo "... Players.i"
	@echo "... Players.s"
	@echo "... Sde.o"
	@echo "... Sde.i"
	@echo "... Sde.s"
	@echo "... Ship.o"
	@echo "... Ship.i"
	@echo "... Ship.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

